//! Assembly text emitter.
//!
//! Writes the final `.asm` file for the **v6asm** assembler targeting
//! the Vector 06 computer.  The emitter prepends the standard header
//! (`ORG`, entry-point jump) and appends a runtime-library section
//! marker after the code-generator output.

use std::io::Write;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Write a complete `.asm` file to `output_path`.
///
/// The file contains, in order:
///
/// 1. A header comment identifying the compiler.
/// 2. `ORG 0x100` – the standard Vector 06 load address.
/// 3. `JMP main` – entry-point jump.
/// 4. All assembly lines produced by the code generator / peephole optimizer.
/// 5. A runtime-library section marker (the actual runtime is linked
///    separately).
pub fn emit_asm(code_lines: &[String], output_path: &str) -> std::io::Result<()> {
    let mut f = std::fs::File::create(output_path)?;

    // Header
    writeln!(f, "; Generated by v6c compiler")?;
    writeln!(f)?;

    // Origin
    writeln!(f, "\tORG 0x100")?;
    writeln!(f)?;

    // Entry point
    writeln!(f, "\tJMP main")?;
    writeln!(f)?;

    // Code from the code generator
    for line in code_lines {
        writeln!(f, "{}", line)?;
    }

    // Runtime library marker
    writeln!(f)?;
    writeln!(f, "; --- runtime library ---")?;
    writeln!(f, "; (linked separately)")?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    static COUNTER: AtomicU32 = AtomicU32::new(0);

    /// Helper: emit into a uniquely-named file and return its contents.
    fn emit_and_read(lines: &[String]) -> String {
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = format!("test_emit_output_{}.asm", id);
        emit_asm(lines, &path).expect("emit_asm failed");
        let contents = std::fs::read_to_string(&path).expect("read failed");
        let _ = std::fs::remove_file(&path);
        contents
    }

    #[test]
    fn header_and_org_present() {
        let out = emit_and_read(&[]);
        assert!(out.starts_with("; Generated by v6c compiler"));
        assert!(out.contains("\tORG 0x100"));
    }

    #[test]
    fn entry_point_jump() {
        let out = emit_and_read(&[]);
        assert!(out.contains("\tJMP main"));
    }

    #[test]
    fn code_lines_emitted() {
        let lines = vec![
            "main:".to_string(),
            "\tMVI A,0".to_string(),
            "\tRET".to_string(),
        ];
        let out = emit_and_read(&lines);
        assert!(out.contains("main:"));
        assert!(out.contains("\tMVI A,0"));
        assert!(out.contains("\tRET"));
    }

    #[test]
    fn runtime_marker_at_end() {
        let out = emit_and_read(&[]);
        assert!(out.contains("; --- runtime library ---"));
    }

    #[test]
    fn order_is_correct() {
        let lines = vec!["\tNOP".to_string()];
        let out = emit_and_read(&lines);

        let org_pos = out.find("\tORG 0x100").unwrap();
        let jmp_pos = out.find("\tJMP main").unwrap();
        let nop_pos = out.find("\tNOP").unwrap();
        let rt_pos = out.find("; --- runtime library ---").unwrap();

        assert!(org_pos < jmp_pos);
        assert!(jmp_pos < nop_pos);
        assert!(nop_pos < rt_pos);
    }
}
