//! Assembly text emitter.
//!
//! Writes the final `.asm` file for the **v6asm** assembler targeting
//! the Vector 06 computer.  The emitter prepends the standard header
//! (`ORG`, entry-point jump, CRT0 startup) and appends the runtime
//! library routines that are actually referenced by the generated code.

use std::io::Write;

use crate::runtime;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Write a complete `.asm` file to `output_path`.
///
/// The file contains, in order:
///
/// 1. A header comment identifying the compiler.
/// 2. `ORG 0x100` – the standard Vector 06 load address.
/// 3. `JMP _start` – jump to runtime startup.
/// 4. CRT0   – stack init, call to main, HLT.
/// 5. All assembly lines produced by the code generator / peephole optimizer.
/// 6. Referenced runtime library routines (auto-detected from CALL/JMP).
pub fn emit_asm(code_lines: &[String], output_path: &str) -> std::io::Result<()> {
    let mut f = std::fs::File::create(output_path)?;

    // Header
    writeln!(f, "; Generated by v6c compiler")?;
    writeln!(f)?;

    // Origin
    writeln!(f, "\tORG 0x100")?;
    writeln!(f)?;

    // Entry point — jump to CRT0 startup
    writeln!(f, "\tJMP _start")?;
    writeln!(f)?;

    // CRT0 startup code
    writeln!(f, "; --- crt0 startup ---")?;
    for line in runtime::crt0_asm().lines() {
        // Skip comment-only header lines already in the source
        if line.starts_with(';') && !line.contains("_start") {
            continue;
        }
        writeln!(f, "{}", line)?;
    }
    writeln!(f)?;

    // Code from the code generator
    for line in code_lines {
        writeln!(f, "{}", line)?;
    }

    // Runtime library — include only the modules that are referenced
    writeln!(f)?;
    writeln!(f, "; --- runtime library ---")?;
    let rt = runtime::collect_runtime(code_lines);
    if !rt.is_empty() {
        write!(f, "{}", rt)?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    static COUNTER: AtomicU32 = AtomicU32::new(0);

    /// Helper: emit into a uniquely-named file and return its contents.
    fn emit_and_read(lines: &[String]) -> String {
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = format!("test_emit_output_{}.asm", id);
        emit_asm(lines, &path).expect("emit_asm failed");
        let contents = std::fs::read_to_string(&path).expect("read failed");
        let _ = std::fs::remove_file(&path);
        contents
    }

    #[test]
    fn header_and_org_present() {
        let out = emit_and_read(&[]);
        assert!(out.starts_with("; Generated by v6c compiler"));
        assert!(out.contains("\tORG 0x100"));
    }

    #[test]
    fn entry_point_jump() {
        let out = emit_and_read(&[]);
        assert!(out.contains("\tJMP _start"));
    }

    #[test]
    fn crt0_startup_present() {
        let out = emit_and_read(&[]);
        assert!(out.contains("_start:"));
        assert!(out.contains("LXI SP"));
        assert!(out.contains("CALL main"));
        assert!(out.contains("HLT"));
    }

    #[test]
    fn code_lines_emitted() {
        let lines = vec![
            "main:".to_string(),
            "\tMVI A,0".to_string(),
            "\tRET".to_string(),
        ];
        let out = emit_and_read(&lines);
        assert!(out.contains("main:"));
        assert!(out.contains("\tMVI A,0"));
        assert!(out.contains("\tRET"));
    }

    #[test]
    fn runtime_marker_at_end() {
        let out = emit_and_read(&[]);
        assert!(out.contains("; --- runtime library ---"));
    }

    #[test]
    fn runtime_included_when_needed() {
        let lines = vec![
            "main:".to_string(),
            "\tCALL __mul16".to_string(),
            "\tRET".to_string(),
        ];
        let out = emit_and_read(&lines);
        assert!(out.contains("__mul16:"), "runtime __mul16 should be included");
    }

    #[test]
    fn order_is_correct() {
        let lines = vec!["\tNOP".to_string()];
        let out = emit_and_read(&lines);

        let org_pos = out.find("\tORG 0x100").unwrap();
        let jmp_pos = out.find("\tJMP _start").unwrap();
        let nop_pos = out.find("\tNOP").unwrap();
        let rt_pos = out.find("; --- runtime library ---").unwrap();

        assert!(org_pos < jmp_pos);
        assert!(jmp_pos < nop_pos);
        assert!(nop_pos < rt_pos);
    }
}
