; Generated by v6c compiler

	.org 0x100

	JMP _start

; --- crt0 startup ---
; The emitter writes ORG 0x100 and JMP _start before including

; _start — runtime entry point
_start:
	LXI SP,0xF800		; set stack below screen memory
	CALL main
	HLT			; halt after main returns

; --- code section ---
; function mix
mix:
	SHLD _l_mix_x
	SHLD _l_mix_y
	LHLD _l_mix_x
	LHLD _l_mix_y
	SHLD __spill_0
	XCHG
	LHLD __spill_0
	DAD D
	SHLD __spill_1
	SHLD _l_mix_s
	LXI H,0
	SHLD _l_mix_i
	LXI H,16
	LXI H,_g_g_arr
	SHLD __spill_2
	LXI H,255
	SHLD __spill_3
	LXI H,1
	SHLD __spill_4
	LXI H,0
	SHLD __spill_5
	LXI H,1
	SHLD __spill_6
L0:
	LHLD _l_mix_i
	SHLD __spill_7
	LHLD __spill_2
	XCHG
	MOV A,H
	SUB D
	JNZ __cmp_done___cg_0
	MOV A,L
	SUB E
__cmp_done___cg_0:
	JM __cg_0
	LXI H,0
	JMP __cg_1
__cg_0:
	LXI H,1
__cg_1:
	SHLD __spill_8
	MOV A,H
	ORA L
	JZ L1
	LHLD _l_mix_s
	LHLD _l_mix_i
	SHLD __spill_9
	LXI D,2
	CALL __mul16
	XCHG
	SHLD __spill_10
	LHLD __spill_3
	DAD D
	SHLD __spill_11
	MOV E,M
	INX H
	MOV D,M
	XCHG
	SHLD __spill_12
	LHLD _l_mix_i
	SHLD __spill_13
	XCHG
	LHLD __spill_13
	DAD D
	SHLD __spill_14
	LHLD __spill_4
	XCHG
	MOV A,L
	ANA E
	MOV L,A
	MOV A,H
	ANA D
	MOV H,A
	SHLD __spill_15
	XCHG
	LHLD __spill_9
	DAD D
	SHLD __spill_16
	SHLD _l_mix_s
	LHLD __spill_5
	XCHG
	MOV A,L
	ANA E
	MOV L,A
	MOV A,H
	ANA D
	MOV H,A
	SHLD __spill_17
	LHLD __spill_6
	XCHG
	MOV A,L
	SUB E
	JNZ __cg_3
	MOV A,H
	SUB D
	JZ __cg_2
	LXI H,0
	JMP __cg_3
__cg_2:
	LXI H,1
__cg_3:
	SHLD __spill_18
	MOV A,H
	ORA L
	JZ L2
	LHLD _l_mix_s
	LHLD _g_g_a
	SHLD __spill_19
	XCHG
	LHLD __spill_19
	DAD D
	SHLD __spill_20
	SHLD _l_mix_s
	JMP L3
L2:
	LHLD _l_mix_s
	LHLD _g_g_b
	SHLD __spill_21
	XCHG
	LHLD __spill_21
	MOV A,D
	CMA
	MOV D,A
	MOV A,E
	CMA
	MOV E,A
	INX D
	DAD D
	SHLD __spill_22
	SHLD _l_mix_s
L3:
	LHLD _l_mix_i
	LHLD __spill_7
	XCHG
	DAD D
	SHLD __spill_23
	SHLD _l_mix_i
	JMP L0
L1:
	LHLD _l_mix_s
	RET
; function main
main:
	SHLD _l_main_argc
	SHLD _l_main_argv
	LHLD _l_main_argc
	LHLD _l_main_argv
	LXI H,0
	SHLD _l_main_i
	LXI H,16
	LXI H,_g_g_arr
	SHLD __spill_24
	LXI H,3
	SHLD __spill_25
	LXI H,1
	SHLD __spill_26
	LXI H,1
	SHLD __spill_27
L4:
	LHLD _l_main_i
	SHLD __spill_28
	LHLD __spill_24
	XCHG
	MOV A,H
	SUB D
	JNZ __cmp_done___cg_4
	MOV A,L
	SUB E
__cmp_done___cg_4:
	JM __cg_4
	LXI H,0
	JMP __cg_5
__cg_4:
	LXI H,1
__cg_5:
	SHLD __spill_29
	MOV A,H
	ORA L
	JZ L5
	LHLD _l_main_i
	LXI D,2
	CALL __mul16
	XCHG
	SHLD __spill_30
	LHLD __spill_25
	DAD D
	SHLD __spill_31
	LHLD _l_main_i
	SHLD __spill_32
	LHLD __spill_26
	XCHG
	CALL __mul16
	SHLD __spill_33
	LHLD __spill_27
	XCHG
	DAD D
	SHLD __spill_34
	XCHG
	LHLD __spill_32
	MOV M,E
	INX H
	MOV M,D
	LHLD _l_main_i
	LHLD __spill_28
	XCHG
	DAD D
	SHLD __spill_35
	SHLD _l_main_i
	JMP L4
L5:
	LXI H,11
	LXI H,7
	SHLD __spill_36
	SHLD __spill_37
	XCHG
	LHLD __spill_36
	CALL mix
	SHLD _l_main_z
	RET
; --- data section ---
_g_g_a:
	DB 3
	DB 0
_g_g_b:
	DB 5
	DB 0
_g_g_arr:
	.STORAGE 32
_l_mix_x:
	.STORAGE 2
_l_mix_y:
	.STORAGE 2
_l_mix_i:
	.STORAGE 2
_l_mix_s:
	.STORAGE 2
_l_main_argc:
	.STORAGE 2
_l_main_argv:
	.STORAGE 2
_l_main_i:
	.STORAGE 2
_l_main_z:
	.STORAGE 2
__spill_0:
	.STORAGE 2
__spill_1:
	.STORAGE 2
__spill_2:
	.STORAGE 2
__spill_3:
	.STORAGE 2
__spill_4:
	.STORAGE 2
__spill_5:
	.STORAGE 2
__spill_6:
	.STORAGE 2
__spill_7:
	.STORAGE 2
__spill_8:
	.STORAGE 2
__spill_9:
	.STORAGE 2
__spill_10:
	.STORAGE 2
__spill_11:
	.STORAGE 2
__spill_12:
	.STORAGE 2
__spill_13:
	.STORAGE 2
__spill_14:
	.STORAGE 2
__spill_15:
	.STORAGE 2
__spill_16:
	.STORAGE 2
__spill_17:
	.STORAGE 2
__spill_18:
	.STORAGE 2
__spill_19:
	.STORAGE 2
__spill_20:
	.STORAGE 2
__spill_21:
	.STORAGE 2
__spill_22:
	.STORAGE 2
__spill_23:
	.STORAGE 2
__spill_24:
	.STORAGE 2
__spill_25:
	.STORAGE 2
__spill_26:
	.STORAGE 2
__spill_27:
	.STORAGE 2
__spill_28:
	.STORAGE 2
__spill_29:
	.STORAGE 2
__spill_30:
	.STORAGE 2
__spill_31:
	.STORAGE 2
__spill_32:
	.STORAGE 2
__spill_33:
	.STORAGE 2
__spill_34:
	.STORAGE 2
__spill_35:
	.STORAGE 2
__spill_36:
	.STORAGE 2
__spill_37:
	.STORAGE 2

; --- runtime library ---
; mul16.asm — 16-bit unsigned multiply for Intel 8080
;
; Entry:  DE = multiplicand, HL = multiplier  (same as codegen convention)
; Exit:   HL = DE * HL  (low 16 bits)
; Clobbers: A, B, C, D, E, flags

__mul16:
	MOV B,H		; BC = multiplier
	MOV C,L
	LXI H,0	; HL = result = 0
	MOV A,B		; check if multiplier is zero
	ORA C
	RZ		; if multiplier == 0, return 0
__mul16_loop:
	MOV A,C		; test low bit of BC
	RAR
	JNC __mul16_skip
	DAD D		; result += multiplicand
__mul16_skip:
	; shift multiplicand left (DE <<= 1)
	MOV A,E
	ADD A
	MOV E,A
	MOV A,D
	ADC A
	MOV D,A
	; shift multiplier right (BC >>= 1)
	MOV A,B
	ORA A
	RAR
	MOV B,A
	MOV A,C
	RAR
	MOV C,A
	; check if multiplier is zero
	ORA B
	JNZ __mul16_loop
	RET

