; Generated by v6c compiler

	.org 0x100

	JMP _start

; --- crt0 startup ---
; The emitter writes ORG 0x100 and JMP _start before including

; _start — runtime entry point
_start:
	LXI SP,0xF800		; set stack below screen memory
	CALL main
	HLT			; halt after main returns

; --- code section ---
; function main
main:
; C_LINE 7
	XRA A
	STA _l_main_i
; C_LINE 8
	LXI H,16
; C_LINE 9
	LXI H,3
	SHLD __spill_0
	LXI H,1
	SHLD __spill_1
; C_LINE 10
	LXI H,1
	SHLD __spill_2
; C_LINE 8
L0:
	LDA _l_main_i
	MOV L,A
	ORA A
	JP __cg_0
	MVI H,255
	JMP __cg_1
__cg_0:
	MVI H,0
__cg_1:
	SHLD __spill_3
	LHLD __spill_0
	XCHG
	MOV A,H
	SUB D
	JNZ __cmp_done___cg_2
	MOV A,L
	SUB E
__cmp_done___cg_2:
	JM __cg_2
	LXI H,0
	JMP __cg_3
__cg_2:
	LXI H,1
__cg_3:
	SHLD __spill_4
	MOV A,H
	ORA L
	JZ L1
; C_LINE 9
	LDA _l_main_i
	MOV L,A
	ORA A
	JP __cg_4
	MVI H,255
	JMP __cg_5
__cg_4:
	MVI H,0
__cg_5:
	LHLD __spill_1
	XCHG
	CALL __mul16
	SHLD __spill_5
	LHLD __spill_2
	XCHG
	DAD D
	SHLD __spill_6
	SHLD _l_main_z
; C_LINE 10
	LDA _l_main_i
	MOV L,A
	ORA A
	JP __cg_6
	MVI H,255
	JMP __cg_7
__cg_6:
	MVI H,0
__cg_7:
	LHLD __spill_3
	XCHG
	DAD D
	SHLD __spill_7
	MOV A,L
	STA _l_main_i
	JMP L0
L1:
; C_LINE 13
	LHLD _l_main_z
	RET
; --- data section ---
_l_main_i:
	.STORAGE 1
_l_main_z:
	.STORAGE 2
__spill_0:
	.STORAGE 2
__spill_1:
	.STORAGE 2
__spill_2:
	.STORAGE 2
__spill_3:
	.STORAGE 2
__spill_4:
	.STORAGE 2
__spill_5:
	.STORAGE 2
__spill_6:
	.STORAGE 2
__spill_7:
	.STORAGE 2

; --- runtime library ---
; mul16.asm — 16-bit unsigned multiply for Intel 8080
;
; Entry:  DE = multiplicand, HL = multiplier  (same as codegen convention)
; Exit:   HL = DE * HL  (low 16 bits)
; Clobbers: A, B, C, D, E, flags

__mul16:
	MOV B,H		; BC = multiplier
	MOV C,L
	LXI H,0	; HL = result = 0
	MOV A,B		; check if multiplier is zero
	ORA C
	RZ		; if multiplier == 0, return 0
__mul16_loop:
	MOV A,C		; test low bit of BC
	RAR
	JNC __mul16_skip
	DAD D		; result += multiplicand
__mul16_skip:
	; shift multiplicand left (DE <<= 1)
	MOV A,E
	ADD A
	MOV E,A
	MOV A,D
	ADC A
	MOV D,A
	; shift multiplier right (BC >>= 1)
	MOV A,B
	ORA A
	RAR
	MOV B,A
	MOV A,C
	RAR
	MOV C,A
	; check if multiplier is zero
	ORA B
	JNZ __mul16_loop
	RET

